# Site settings
name: 闫强
location: 北京
company: 搜狐畅游
position: 自然语言处理实习生
github: https://github.com/yanqiangmiffy
user: https://www.jianshu.com/u/261e23a40f71
phone: 1580424XXXX
email: yanqiangmiffy@gmail.com

baseurl: "/resume"

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown

